### ISSUE TITLE
Ownership Update on supermarket and Release Request

### ISSUE THREAD

**Issue by EdHurtig** [evertrue/storage-cookbook#6]
@eherot could you transfer ownership of this cookbook over to the Evertrue account? I need to push a release but unfortunately can't do so while Evertrue is not the owner or a collaborator.

**Comment by eherot** [comment]
Transferring ownership is a PITA. I added you and ET as collaborators.

**Comment by eherot** [comment]
Note that we SHOULD transfer ownership but we should do that while sitting together.

**Comment by EdHurtig** [comment]
Pushed release, thanks!
